// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWENh10iEvv7VpyBZQu8HRRiYO8myV3o0',
    appId: '1:166736659018:web:ab96b783e8980680c45cb3',
    messagingSenderId: '166736659018',
    projectId: 'comanda-b935f',
    authDomain: 'comanda-b935f.firebaseapp.com',
    storageBucket: 'comanda-b935f.appspot.com',
    measurementId: 'G-GCEB00T5K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqcjA-akE6MbRjfkc8HvJZpMYTZNER_M',
    appId: '1:166736659018:android:4cb34295ee21b3dac45cb3',
    messagingSenderId: '166736659018',
    projectId: 'comanda-b935f',
    storageBucket: 'comanda-b935f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xr4plQ94mOoaNNOPuWuaJAtt5vj4B6U',
    appId: '1:166736659018:ios:6e580c8590c18e96c45cb3',
    messagingSenderId: '166736659018',
    projectId: 'comanda-b935f',
    storageBucket: 'comanda-b935f.appspot.com',
    iosBundleId: 'com.example.comanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xr4plQ94mOoaNNOPuWuaJAtt5vj4B6U',
    appId: '1:166736659018:ios:6e580c8590c18e96c45cb3',
    messagingSenderId: '166736659018',
    projectId: 'comanda-b935f',
    storageBucket: 'comanda-b935f.appspot.com',
    iosBundleId: 'com.example.comanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWENh10iEvv7VpyBZQu8HRRiYO8myV3o0',
    appId: '1:166736659018:web:e823c0bfcfea989ec45cb3',
    messagingSenderId: '166736659018',
    projectId: 'comanda-b935f',
    authDomain: 'comanda-b935f.firebaseapp.com',
    storageBucket: 'comanda-b935f.appspot.com',
    measurementId: 'G-PLF39TWJ01',
  );
}
